### ISSUE TITLE
Function parameters are not correctly formatted in documentation

### ISSUE THREAD

**Issue by TedTed** [opendp/smartnoise-sdk#205]
On [this documentation page](https://opendifferentialprivacy.github.io/whitenoise-samples/docs/api/system/sql/private_reader.html) and on all others on the same doc, the `params` are not formatted correctly, which makes it quite hard to read.

**Comment by joshua-oss** [comment]
Doc build system now uses Sphinx, which picks up the rst parameters: https://docs.opendp.org/en/latest/smartnoise/api-reference/index.html
