### ISSUE TITLE
Switch RL learner to use Evaluator interface

### ISSUE THREAD

**Issue by ankit-oss** [opendp/smartnoise-sdk#294]
Currently the learner calls in the internal functions in _dp_verification.py and those are on track to deprecate. All the new code is behind interfaces. Every algorithm (query) has to be behind a PrivacyAlgorithm interface with prepare, release, actual_release methods. The evaluator just has one function call .evaluate which gives back all the metrics RL learner will. 

The benchmark function can take in multiple query strings in one shot but I believe RL learner won't use this because it needs to update after every evaluator result.

**Comment by joshua-oss** [comment]
This is done
