### ISSUE TITLE
Dataset size requirements for OpenDP use

### ISSUE THREAD

**Issue by JaredFreeman** [opendp/smartnoise-sdk#297]
How small a dataset can OpenDP reliably privatize? We'd like to propose to our IRB that we protect some human subjects datasets with OpenDP rather than locks on filedrawers, and secure servers. However, I'm unable to assess whether smaller datasets (e.g., 14 Ss x 8 survey items) can be effectively privatized. I'd welcome your advice or a pointer to the literature.

**Comment by eedeleon** [comment]
Hi @JaredFreeman , Dataset size is definitely tricky when it comes to DP. In general the tools within OpenDP SmartNoise are meant to protect user level, in many cases based of row level privacy. 

These protections will still hold for small datasets, however, the utility of the results tend to be worst. 

During our evaluation under review we saw larger datasets performing better across most metrics for synthetic data generation.
![image](https://user-images.githubusercontent.com/31962564/98056622-5e930180-1e0e-11eb-8b34-ae5545e667e1.png)

However, there are more ways to try to capture some of the underlying information that may yield better utility such as private [synopsis ](https://github.com/opendifferentialprivacy/smartnoise-samples/blob/master/data/Synopsis.ipynb)or [analysis](https://github.com/opendifferentialprivacy/smartnoise-samples/blob/master/analysis/tutorial_mental_health_in_tech_survey.ipynb).

A notebook that could help see the tradeoff with sample size and results is https://github.com/opendifferentialprivacy/smartnoise-samples/blob/master/analysis/basic_data_analysis.ipynb where tuning the sample size and rerunning the analysis should give some intuition of how the utility changes
