### ISSUE TITLE
Visualizing the ast graph could make debugging easier

### ISSUE THREAD

**Issue by vserret** [opendp/smartnoise-sdk#345]
When rewriting a parsed query for making it differentially private, some branches of the original AST are handwritten and this could be a source of bugs. 
The rewritten query should not change when parsed, i.e.`private_query == QueryParser().parse(str(private_query)))` must be `True`. 

**Visualizing a parsed query could make debugging easier by identifying at a glance the incorrect nodes of the AST.** 

Example:

The parsed `SELECT SUM(age) AS my_sum FROM pums.pums GROUP BY age` could be represented as: 

![parsed_query](https://user-images.githubusercontent.com/22152801/112838426-54afba80-909d-11eb-816b-ff278edb27ba.png)

If we break the grammar rules by doing `query.agg = 'GROUP BY age'`, the GROUP BY clause of the parsed query is now a `str` instead of an `Aggregate` object. 
By displaying `private_query` and the `QueryParser().parse(str(private_query)))`, we could see immediately the dissimilarities between the two. 
Besides, we could color the incorrect type nodes to make the changes more apparent. 

![wrong_parsed_query](https://user-images.githubusercontent.com/22152801/112838436-57121480-909d-11eb-9151-5736c53484be.png)

**I propose a function which permits to represent any parsed query or bits of query as a graphviz `Digraph`.**
Each node of the ast is then recursively visited to built the graph. Do you think that could be useful to integrate it in smartnoise ?

**Comment by joshua-oss** [comment]
This is a great idea!

(Note that I have opened issue #346 to track the round-tripping issues, and we can discuss the visualization here).  Tagging @eedeleon into the discussion.

Where on the API should we put the functionality? One place to put this functionality could be as a method on `_ast.tokens.Sql`, from which all parsed AST nodes inherit.  So code like this would work:

```
query_parser = QueryParser(...)
q = query_parser.query('SELECT SUM(Foo) FROM Bar')
dot = q.visualize()

aggs = q.find_nodes(AggFunction)
for agg in aggs:
   dot = agg.visualize()
   ...
```

Any other options we should consider?

I assume that callers will want to call this API from console applications and Jupyter, with server and other applications being less common.  My understanding is that `Graphviz` in Jupyter will automatically convert to SVG to display in the browser, so callers will not need different code depending on the environment.  For callers who want to manually create PNG, etc, this seems easy enough that we wouldn't need helper methods.

**Comment by vserret** [comment]
I was thinking of having an independent script in `_ast/`. So you don't add a graphviz dependency for the user who just want to have the dp result and does not want to plot the AST.

**Comment by joshua-oss** [comment]
This is completed in #349 and deployed to PyPi
