### ISSUE TITLE
Improving round-tripping of AST

### ISSUE THREAD

**Issue by joshua-oss** [opendp/smartnoise-sdk#346]
Issue #345 is about visualizing the AST, but mentions another issue, where the rewriter still does some manual creation of SQL, which could lead to bugs in round-tripping.  Creating this bug to track that issue separately.

One example of this is line 159 of `private_rewriter.py`, where the rewriter creates an `AliasedRelation`, which gets parsed back to a `Relation` with a nested `AliasedSubquery`.  This works as intended, but anyone relying on the ASTs to match would have an unpleasant surprise.  This should be straightforward to fix.  

Another example is the way that the rewriter generates nested expressions for all of the outer aggregates.  These get parsed away on round-trip.  This doesn't cause any apparent bugs, but seems dangerous, especially as we extend functionality to support more complex subqueries or joins.  This will be trickier to fix.

Two related issues, line 211 does fragment parsing for row_num, and 263 does fragment parsing for clamping expression.  These should be straightforward to fix.

There may be other issues not enumerated here, please add to this bug.

I have uploaded a more detailed discussion of internals that may be helpful in auditing: https://github.com/opendp/smartnoise-sdk/blob/main/papers/SQL%20Design.pdf

**Comment by vserret** [comment]
When I rewrite the query `SELECT age, SUM(income) FROM pums.pums WHERE income > 0 GROUP BY age`, 

I have (before reparsing): 

![dp_query](https://user-images.githubusercontent.com/22152801/113103677-dd466c00-91ff-11eb-979c-31744e3e5628.png)

And then when I reparse it: 

![reparsed_dp_query](https://user-images.githubusercontent.com/22152801/113103707-e9cac480-91ff-11eb-8cc6-f1998d49b24e.png)

For example, we notice that: 
- Alias must be `Identifier` not `str`
- Operator must be `Op` not `str`
- Case expressions should be declared with `CaseExpression`, not `Expression`

I have already made the changes in my local branch. Maybe I could push it to smartnoise ? 

This opens a new issue :) : I think that would be easier for rewriting if the all the bits of the AST where typed

**Comment by joshua-oss** [comment]
Yes, these look good.  Thanks much for reporting and patching these.  Eddie will sync with you for directions on the pull request.

Regarding the comment on easier for rewriting if the bits of the AST are typed, can you clarify?  The object model of the AST is a type hierarchy.  Do you mean the rewriter should only ever use the most specific typed objects (i.e. don't use Expression), or do you mean we should use type hints/annotations?  Or something else?

**Comment by vserret** [comment]
I was thinking about type hints/annotations

**Comment by joshua-oss** [comment]
I'm in favor of better type information.  The grammar and basic approach here were ported from a system we first built in Scala, which has great support for both static and runtime types, and pattern matching.  When I initially tried to use the Python type annotations, it was not a great experience.  Backwards compatibility issues for older versions of Python, issues with circular and forward references, static type checking didn't work in many of the most important scenarios, poor integration with the documentation tools, etc.  Now that we have a requirement for Python 3.6+, and with new features coming in, like pattern matching in 3.10, it might be time to revisit.

**Comment by joshua-oss** [comment]
All issues fixed in #350
