### ISSUE TITLE
Sql.expression() does not follow the Identifier rule defined by the gammar

### ISSUE THREAD

**Issue by vserret** [opendp/smartnoise-sdk#352]
When `Sql.symbol_name` is define as `str(hex(hash(self) % (2 ** 16)))` [here](https://github.com/opendp/smartnoise-sdk/blob/4863a858fd54d2c024af8ddc95c2042b976d058b/sdk/opendp/smartnoise/_ast/tokens.py#L96), this name doesn't follow the [grammar](https://github.com/opendp/smartnoise-sdk/blob/4863a858fd54d2c024af8ddc95c2042b976d058b/sdk/opendp/smartnoise/sql/parser/SqlSmall.g4#L359), since an identifier should begin with a letter.

So when you are using `Scope.push_name(expression)` in private_rewriter.py, `expression`  will be renamed by `expression.symbol_name` ([here](https://github.com/opendp/smartnoise-sdk/blob/4863a858fd54d2c024af8ddc95c2042b976d058b/sdk/opendp/smartnoise/sql/private_rewriter.py#L331)) and the parsing will fail. 

What do you think of replacing `str(hex(hash(self) % (2 ** 16)))` by `f"alias_{hex(hash(self) % (2 ** 16))}"` ?

Besides, for following the grammar, `Sql.symbol_name` should return an `Identifier`

**Comment by joshua-oss** [comment]
Yes, those are both good ideas.  Returning symbol_name as Identifier should be safe, since we always wrap in `str()` when sending in to `push_name`.

**Comment by joshua-oss** [comment]
Fixed by #355
