### ISSUE TITLE
Trialling reidentification attack notebook and MWEM synthesiser not recognising Q-Count

### ISSUE THREAD

**Issue by MaddieGibbons** [opendp/smartnoise-sdk#371]
Hi,

I'm cureently trying to trial the reidentification notbook from thee whitepapers - I've downloaded the conda environment listed, and ran everything in the notebook (as provided) but when I run this kernel

%%time
# Apply the synthesizer to the data set
synthetic_data = MWEMSynthesizer(
                        Q_count = 400,
                        epsilon = 3.00,
                        iterations = 60,
                        mult_weights_iterations = 40,
                        splits = [],
                        split_factor = 1)

I get the following error:

TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

TypeError: __init__() got an unexpected keyword argument 'Q_count'

Is there anything that could be causing this? all of the packages import as expected, and the previous kernels run normally - it's just the MWEM synthesiser.

**Comment by joshua-oss** [comment]
Ah, that looks like a typo in the notebook.  The parameter is all lower case, so changing it to `q_count` should fix the error.

**Comment by MaddieGibbons** [comment]
Well now I feel very daft – thanks – it worked! xD

**Comment by joshua-oss** [comment]
Not at all, that was our bug!  We appreciate you reporting it.  I've submitted a pull request to fix the notebook: https://github.com/opendp/smartnoise-samples/pull/94

**Comment by joshua-oss** [comment]
Fixed in #94
