### ISSUE TITLE
query.row_privacy is not set when the query has no Aggregates with TableColumn

### ISSUE THREAD

**Issue by vserret** [opendp/smartnoise-sdk#380]
If the query has no table column (eg: `query = SELECT COUNT(*) FROM census.census` or `SELECT COUNT(1) FROM census.census` or `'SELECT income, COUNT(*) FROM pums.pums GROUP BY income`), if you do:
```
parsed_query = QueryParser().query(query)
parsed_query.load_symbols(metadata)
```
Then `parsed_query = False` even if `metadata`specifies the contrary. 

While it works when sending `SELECT COUNT(age) FROM census.census`

**Comment by joshua-oss** [comment]
Fixed by #378
