### ISSUE TITLE
Add Accuracy

### ISSUE THREAD

**Issue by joshua-oss** [opendp/smartnoise-sdk#382]
We previously exposed accuracy information on `TypedRowset`, which is now deprecated.  Result rowsets now use the standard DB-API tuples format, and optionally return Pandas data frames, with neither API having a place to store accuracy information.

Proposal is to add an API on `private_reader` that will parse a query and calculate the 95% accuracy interval for each column in the query, returning the bounds as a vector.

```
query = 'SELECT COUNT(*) FROM PUMS.PUMS'
private_reader = PrivateReader(reader, meta, 1.0)
accuracy = private_reader.get_accuracy(query)
print(accuracy[0])
```

Because we need metadata to calculate sensitivity, `get_accuracy` will require parsing and symbol resolution.  The code that calculates sensitivity is currently in the `execute()` method of `PrivateReader`, so we should pull that out into a shared routine that can be called from both methods.  One option would be to add sensitivity to `Query.load_symbols`.

https://github.com/opendp/smartnoise-sdk/blob/main/papers/DP_SQL_budget.pdf

**Comment by joshua-oss** [comment]
We should allow arbitrary accuracy bounds to be requested, such as 95% and 99%.  One way to expose this would be:

`accuracy = private_reader.get_accuracy(query, alphas=[0.01, 0.05])`

**Comment by khueyama** [comment]
@joshua-oss thanks so much for your help getting this implemented. The calling pattern with a list of `alphas` to calculate would be incredibly helpful.

**Comment by joshua-oss** [comment]
I'm realizing that the above calling pattern would work for only SUM and COUNT queries, since the other statistics need the noisy count (denominator) to compute accuracy.  The only way to get the noisy count is to actually execute the query.  We could execute the query in `get_accuracy`, but then the calling pattern would result in the query being executed twice.  So it seems best to just return accuracy with the `execute()` method.  Two possible approaches:

1. Allow `execute()` to return the rowset and the accuracy:

```python
result, accuracy = private_reader.execute(query, alphas) # has accuracy
result = private_reader.execute(query) # no alphas provided, so no accuracy
```

This has the advantage of being consistent with current calling patterns, and the path without accuracy would continue to conform to DB-API interface.  It has the disadvantage that the number of return values will differ based on whether or not alphas are passed in.  In practice, this shouldn't be a problem, because the caller will only pass alphas when expecting two return values.  But this approach is probably not pythonic.

2.  Make a new method, e.g. `execute_with_accuracy()`:

```python
result, accuracy = private_reader.execute_with_accuracy(query, alphas)
result = private_reader.execute(query) #  no accuracy
```

This has the advantage of being explicit, but feels more cumbersome.

Another important implication of statistics needing the noisy count for accuracy: we will need to return accuracy bounds for each row of the output.  For example, if we do `SELECT educ, AVG(income) FROM PUMS GROUP BY educ`, the partitions with fewer members will have worse accuracy.  In this PUMS example, there are ~13 distinct values for `educ`, and the sizes of each partition vary greatly.  We would need to return ~13 rows of accuracy information in this case.  For queries with multiple columns, the `accuracy` return value would be the same length and width as the query results rowset.  I think this is fine, and we could provide code samples to show how to use `zip()` to combine accuracy information with the noisy values.

**Comment by ClaireMcKayBowen** [comment]
@joshua-oss, could you clarify the problem about running the query twice? Is this a computing problem or a methodology problem?

**Comment by joshua-oss** [comment]
@ClaireMcKayBowen, the issue with running query twice is just that the queries may be expensive.  We do have a capability to  cache query output for multiple issues of the same query, but this is geared more towards very high numbers of runs for fairly small result sets (e.g. 10,000 runs of same query in the stochastic evaluator).  In practice, we have some queries that operate on petabytes of data, returning millions of partitions, so caching wouldn't be feasible, and the computation costs enough money to matter.

Regarding the last paragraph, the output would have one row per aggregate partition, and one column for each alpha, for each column.  This means we also need to decide how to group the results.  For example, if we had something like `SELECT race, AVG(income), AVG(educ) GROUP BY race`, requesting two alphas, we have a few choices for how to return:

1. Each row shows two accuracy columns per output column, in column order:

```
('race99', 'race95', 'educ99', 'educ95', 'income99', 'income95'),
(None, None, 3.8, 3.6, 2.6, 2.4)`
```

In this example, we return 2 `None` values for the accuracy of the grouping column, to preserve column order.

2. Each row has one accuracy column per output column, and the column has a tuple that has the same number of items as the alphas passed in:

```
('race', 'educ', 'income'),
( [None, None], [3.8, 3.6], [2.6, 2.4])
```

3. We return multiple accuracy results as a list, with each item in the list being for each alpha, in the same order passed in:

```python
alphas = [0.01, 0.05]
result, accuracy = private_reader.execute(query, alphas)
accuracy99, accuracy95 = accuracy

print(accuracy95)

('race', 'educ', 'income'),
( None, 3.6, 2.4)
```

Note that all of these approaches can optionally return accuracy as Pandas data frame(s), the same as query results can come back as Pandas.

**Comment by ClaireMcKayBowen** [comment]
@joshua-oss Thank you for taking the time to explain this to me! This makes sense.

**Comment by joshua-oss** [comment]
Thinking about this more, it might make sense to put the alphas on the `PrivateReader`.  Assuming we adopt the pattern of #377, this would look something like:

```python
conn = pyodbc.connect(dsn)
privacy = Privacy(epsilon=1.0, alphas=[0.1, 0.5]) 
private_reader = PrivateReader(conn, privacy, meta=meta)
result, accuracy = private_reader.execute_with_accuracy(query)
```

This has the advantage that alphas don't need to be passed on every call to `execute()`.  This is using the second pattern for accuracy above, to avoid inconsistent number of return values.  The long method name still feels cumbersome, perhaps we could find a better name.  Maybe `execute_accuracy()`.  Or we could go ahead and overload `execute()` as above.

```python
result, accuracy = private_reader.execute(query) # works if alphas set on private_reader, fails otherwise
result = private_reader.execute(query) # works if no alphas on private_reader, fails otherwise
```

This means the caller would need to remember if alphas were set on the `PrivateReader` instantiation, and would need to go change all lines that call execute if the presence of alphas list changes.  For example, if the user updated the code that instantiated private reader to add  `alphas`, but then forgot to capture `accuracy` on `execute`, the call would fail.  One way to handle this would be with a positional parameter on `execute` that specifies that accuracy will be returned, like:

```python
result, accuracy = private_reader.execute(query, True) # always works; returns empty accuracy list if alphas not set
result = private_reader.execute(query) # always works
```

**Comment by khueyama** [comment]
@joshua-oss Just my thoughts: Agree that setting the `alphas` on the `PrivateReader` seems easier than having to pass it to every `execute()` call. And `execute_with_accuracy()` or `execute_accuracy()` don't feel that cumbersome, at least compared to the issues with overloading `execute()` you outlined.

**Comment by joshua-oss** [comment]
Accuracy is now merged and published to PyPi.  Code samples of usage:

```
from opendp.smartnoise.metadata.collection import CollectionMetadata
from opendp.smartnoise.sql.parse import QueryParser
from opendp.smartnoise.sql.privacy import Privacy
import pandas as pd
import numpy as np

from opendp.smartnoise.sql import PrivateReader

meta_path = 'datasets/PUMS.yaml'
csv_path = 'datasets/PUMS.csv'

pums = pd.read_csv(csv_path)
meta = CollectionMetadata.from_file(meta_path)
delta = 1/ (1000 * np.sqrt(1000))
privacy = Privacy(epsilon=1.0, delta=delta, alphas=[0.05, 0.01, 0.5])

reader = PrivateReader.from_connection(pums, privacy=privacy, metadata=meta_path)
query = 'SELECT COUNT(income) AS n FROM PUMS.PUMS'

# first, execute without accuracy, loading to a pandas df
print(reader.execute_df(query))

# next, execute with accuracy, using the row iterator syntax
result = reader.execute_with_accuracy(query)
for row, accuracies in result:
    acc95, acc99, acc50 = accuracies
    print(f"{row} with 95% +/-{acc95[0]}")

# now execute with pandas df syntax
result = reader.execute_with_accuracy_df(query)
res, accuracies = result
acc95, acc99, acc50 = accuracies
print(res)
print()
print(acc95)

# now execute 30 times and check odometer
for _ in range(30):
    reader.execute(query)

print(f"Odometer after 30 more runs: {reader.odometer.spent}")




"""
The following code shows how to run multiple trials of a SQL query
more efficiently.  This uses the internal API _execute_ast with the
private setting cache_exact to ensure that the exact SQL query runs
only once.  This is not the recommended syntax for calling accuracy,
but should speed up sampling substantially when large numbers of draws
of the same query are desired.
"""

### Count

query = 'SELECT COUNT(income) AS n FROM PUMS.PUMS'
actual = 1000

q = QueryParser(meta).query(query)

reader = PrivateReader.from_connection(pums, privacy=privacy, metadata=meta_path)

res = reader.execute_with_accuracy(query)

for row, accuracies in res:
    n95, n99, n50 = accuracies
    print(f"{row[0]} --> {n95[0]}, {n99[0]}, {n50[0]}")

counts = []
trials = 1000
for _ in range(trials):
    res = reader._execute_ast(q, cache_exact=True, accuracy=True)
    row, acc = res[1]
    counts.append(row[0])

upper95 = actual + n95[0]
lower95 = actual - n95[0]
upper99 = actual + n99[0]
lower99 = actual - n99[0]
upper50 = actual + n50[0]
lower50 = actual - n50[0]

out95 = sum([c <= lower95 or c >= upper95 for c in counts])
out99 = sum([c <= lower99 or c >= upper99 for c in counts])
out50 = sum([c <= lower50 or c >= upper50 for c in counts])

print(f"{out95/trials} of values are outside the 95% range")
print(f"{out99/trials} of values are outside the 99% range")
print(f"{out50/trials} of values are outside the 50% range")

### Sum

query = 'SELECT SUM(age) AS n FROM PUMS.PUMS'
actual = 44797

q = QueryParser(meta).query(query)

reader = PrivateReader.from_connection(pums, privacy=privacy, metadata=meta_path)

res = reader.execute_with_accuracy(query)

for row, accuracies in res:
    n95, n99, n50 = accuracies
    print(f"{row[0]} --> {n95[0]}, {n99[0]}, {n50[0]}")

counts = []
trials = 1000
for _ in range(trials):
    res = reader._execute_ast(q, cache_exact=True, accuracy=True)
    row, acc = res[1]
    counts.append(row[0])

upper95 = actual + n95[0]
lower95 = actual - n95[0]
upper99 = actual + n99[0]
lower99 = actual - n99[0]
upper50 = actual + n50[0]
lower50 = actual - n50[0]

out95 = sum([c <= lower95 or c >= upper95 for c in counts])
out99 = sum([c <= lower99 or c >= upper99 for c in counts])
out50 = sum([c <= lower50 or c >= upper50 for c in counts])

print(f"{out95/trials} of values are outside the 95% range")
print(f"{out99/trials} of values are outside the 99% range")
print(f"{out50/trials} of values are outside the 50% range")



### Avg

query = 'SELECT AVG(age) AS age FROM PUMS.PUMS'
q = QueryParser(meta).query(query)
actual = 44.797

#query = 'SELECT AVG(age) AS age FROM PUMS.PUMS WHERE educ > 12'
#q = QueryParser(meta).query(query)
#actual = 47.532

reader = PrivateReader.from_connection(pums, privacy=privacy, metadata=meta_path)

res = reader.execute_with_accuracy(query)

for row, accuracies in res:
    n95, n99, n50 = accuracies
    print(f"{row[0]} --> {n95[0]}, {n99[0]}, {n50[0]}")

counts = []
trials = 1000
for _ in range(trials):
    res = reader._execute_ast(q, cache_exact=True, accuracy=True)
    row, acc = res[1]
    counts.append(row[0])

upper95 = actual + n95[0]
lower95 = actual - n95[0]
upper99 = actual + n99[0]
lower99 = actual - n99[0]
upper50 = actual + n50[0]
lower50 = actual - n50[0]

out95 = sum([c <= lower95 or c >= upper95 for c in counts])
out99 = sum([c <= lower99 or c >= upper99 for c in counts])
out50 = sum([c <= lower50 or c >= upper50 for c in counts])

print(f"{out95/trials} of values are outside the 95% range")
print(f"{out99/trials} of values are outside the 99% range")
print(f"{out50/trials} of values are outside the 50% range")


### Variance

query = 'SELECT VAR(age) AS n FROM PUMS.PUMS'
actual = 314.8987

q = QueryParser(meta).query(query)

reader = PrivateReader.from_connection(pums, privacy=privacy, metadata=meta_path)

res = reader.execute_with_accuracy(query)

for row, accuracies in res:
    n95, n99, n50 = accuracies
    print(f"{row[0]} --> {n95[0]}, {n99[0]}, {n50[0]}")

counts = []
trials = 1000
for _ in range(trials):
    res = reader._execute_ast(q, cache_exact=True, accuracy=True)
    row, acc = res[1]
    counts.append(row[0])

upper95 = actual + n95[0]
lower95 = actual - n95[0]
upper99 = actual + n99[0]
lower99 = actual - n99[0]
upper50 = actual + n50[0]
lower50 = actual - n50[0]

out95 = sum([c <= lower95 or c >= upper95 for c in counts])
out99 = sum([c <= lower99 or c >= upper99 for c in counts])
out50 = sum([c <= lower50 or c >= upper50 for c in counts])

print(f"{out95/trials} of values are outside the 95% range")
print(f"{out99/trials} of values are outside the 99% range")
print(f"{out50/trials} of values are outside the 50% range")
```
