### ISSUE TITLE
Link to Smartnoise documentation in README is broken

### ISSUE THREAD

**Issue by staylorUI** [opendp/smartnoise-sdk#398]

**Comment by pdurbin** [comment]
@staylorUI hi! Thanks for opening this issue!

The docs were moved to https://docs.smartnoise.org as part of https://github.com/opendp/docs.smartnoise.org/issues/47

**Comment by joshua-oss** [comment]
Thanks @staylorUI for reporting, and thanks @pdurbin for the correct link.  I have updated the README now.
