### ISSUE TITLE
Looping epsilon in PrivateReader gives UnknownTypeException error

### ISSUE THREAD

**Issue by akash-y** [opendp/smartnoise-sdk#428]
Setting epsilon using values from a list in the PrivateReader throws an UnknownTypeException error. The code works when manually trying to add the values. Epsilon values were generated using np.linspace(0.1, 1, 11)

![image](https://user-images.githubusercontent.com/11901842/142033121-54362162-20fe-4e81-a78e-e2cb725191cf.png)
![image](https://user-images.githubusercontent.com/11901842/142033395-7ce561be-9f00-4f25-a97d-0375d8a8b611.png)

**Comment by Shoeboxam** [comment]
Can you try this instead:

```python
private_reader_censor = PrivateReader(reader_censored, meta, privacy=Privacy(epsilon=float(eps_list_item, delta=float(delta))
```

The problem here is that the eps_list_item is a numpy type, not a native python float type. I'll push a patch that fixes this in the OpenDP library.

**Comment by akash-y** [comment]
works now. thanks!

**Comment by joshua-oss** [comment]
Fixed in opendp https://github.com/opendp/opendp/pull/394
