### ISSUE TITLE
Not working on mac M1

### ISSUE THREAD

**Issue by s-inder-preet** [opendp/smartnoise-sdk#445]
[smartnoise_error.log](https://github.com/opendp/smartnoise-sdk/files/7925255/smartnoise_error.log)
Getting this error while installing smartnoise-synth on a Macbook pro with Apple silicon. 

Used the commmand:
`python3 -m pip install smartnoise-synth`

**Comment by joshua-oss** [comment]
Unfortunately, a few of the packages we depend on still do not have M1 builds.  I use an M1 MacBook, however, and smartnoise-synth works well in using 64-bit python, such as "Miniconda3 MacOSX 64-bit pkg".

**Comment by joshua-oss** [comment]
Fixed in v0.3.0
