### ISSUE TITLE
synth/samples/whitepaper-demos/5-ml-synthetic-data.ipynb does not run by not support continuous values on this synthesizer

### ISSUE THREAD

**Issue by JoaoRodrigues9** [opendp/smartnoise-sdk#447]
After trying to replicate the 5-ml-synthetic-data.ipynb using QUAIL architecture i get the error "ValueError: We don't support continuous values on this synthesizer.  Please discretize values." 
I do not understand how to solve this issue to the provided sample dataset.
I am using smartnoise-synth library with the version 0.2.5 and trying to replicate https://github.com/opendp/smartnoise-sdk/tree/main/synth/samples/whitepaper-demos without sucess.

**Comment by joshua-oss** [comment]
Fixed in #463
