### ISSUE TITLE
Simple sample form MWEM not working

### ISSUE THREAD

**Issue by s-inder-preet** [opendp/smartnoise-sdk#453]
Hi, I have been exploring one of the example notebooks here: https://github.com/opendp/smartnoise-samples/blob/master/whitepaper-demos/5-ml-synthetic-data.ipynb

After fitting MWEM synthesizer I get a strange erro when sampling, could that be fixed. I am using a Mac M1 with anaconda.

![image](https://user-images.githubusercontent.com/23189856/153393689-7e59316a-5a13-4f8f-9444-3ca708a5d92e.png)

**Comment by joshua-oss** [comment]
We've added M1 support in the latest release of smartnoise-synth.

**Comment by joshua-oss** [comment]
Fixed
