### ISSUE TITLE
Support special cases in the grammar for `qualifiedTableName`

### ISSUE THREAD

**Issue by oskarkocol** [opendp/smartnoise-sdk#455]
I run into a couple edge cases related to the identifier following the `FROM` statement. I came across these when spiking support for BigQuery engine so they don't really affect current users. The edge cases may have to be addressed with changes to code outside of the engine specific classes inheriting from `SqlReader` defined [here](https://github.com/opendp/smartnoise-sdk/tree/main/sql/snsql/sql/reader).

### Using table identifiers with a hyphen (`-`)
PostgreSQL and BigQuery engines support table names that contain as long as they are escaped. This definition of the `ESCAPED_IDENTIFIER` does not include hyphens and a statement like ``FROM `data-base`.`schema`.`table` ``
https://github.com/opendp/smartnoise-sdk/blob/186b81721c0f5c9ef9028e56a5ac142e9b362602/sql/snsql/sql/parser/SqlSmall.g4#L471-L476
**Possible solution:** probably something as simple as adding hyphen to the match. For example:
```
    | '"' (LETTER | DIGIT | '_' | ' ' | '-')*? '"'
```

### Escaping the entire table identifier
BigQuery grammar allows escaping the entire table identifier. For example `` `database.schema.table` `` in place of `` `database`.`schema`.`table` ``. This way of escaping is not supported by the parser. I assume that it has to do with the way how identifiers are defined and how later they are reused by: 
https://github.com/opendp/smartnoise-sdk/blob/186b81721c0f5c9ef9028e56a5ac142e9b362602/sql/snsql/sql/parser/SqlSmall.g4#L457-L459

**Possible solution:** I don't see a clear solution and would love to hear your input. My intuition would be to introduce a table specific identifier that would handle different ways to escape the tables ([credit](https://github.com/leonchen83/antlr4-mysql/blob/c75dd9eaf6778604c0ae188ebac0027f47b955e9/MySQL.g4#L1331-L1333)).
```
qualifiedTableName : TABLE_IDENTIFIER

TABLE_IDENTIFIER
    : ((IDENT '.')? IDENT '.')? IDENT
    | '"' TABLE_IDENTIFIER '"'
    | '`' TABLE_IDENTIFIER '`'
    ;
```
But I expect that this would introduce complexity down the dependency that would have to be resolved (`QN2`, `QN3` and `TABLE_IDENTIFIER` match both table and column identifiers). If there is a more succinct way to go about it, I'd love to hear about it.

**Comment by joshua-oss** [comment]
Adding support for hyphen in escaped identifiers looks like a good idea.  In principle, we should also be able to support escaping around the entire fully-qualified object name rather than requiring parts to be escaped individually, but I would want to carefully test in some other engines to see what the behavior is independent of our parser.  For example, if we do something like `database.schema`.table, does that always resolve to a 3-part name in all engines, or do some engines treat the first part as a single part that has an escaped period in it?

**Comment by joshua-oss** [comment]
Fixed
