### ISSUE TITLE
Unsafe noise is used without explicit user confirmation

### ISSUE THREAD

**Issue by TedTed** [opendp/smartnoise-sdk#461]
Hello!

My previous understanding of [issues like these](https://github.com/opendp/opendp/issues/414) is that they did not technically qualify as a vulnerability, because in order to use them, the user has to explicitly opt in to the use of unsafe noise addition routines by enabling the `'floating-point'` option. But apparently, SmartNoise SQL does not require the user to do that, and instead [enables this feature](https://github.com/opendp/smartnoise-sdk/blob/main/sql/snsql/sql/_mechanisms/laplace.py#L34) when needed, without any user interaction.

This sounds like surprising & potentially dangerous behavior, so I thought it was worth flagging.

**Comment by joshua-oss** [comment]
Thanks for flagging this.  We default counts and integer sums to use geometric, but the caller can override this without being warned.  And opendp library currently only exposes unsafe mechanisms for floating point sums.  Either way, we can warn the caller and suggest workarounds when any unsafe mechanisms are selected.

**Comment by joshua-oss** [comment]
Fixed
