### ISSUE TITLE
Gaussian formula looks wrong when epsilon>1

### ISSUE THREAD

**Issue by TedTed** [opendp/smartnoise-sdk#462]
[This line of code](https://github.com/opendp/smartnoise-sdk/blob/main/sql/snsql/sql/_mechanisms/gaussian.py#L35) seems like it can be executed when sensitivity>1000 and epsilon>1. But this formula only holds when epsilon<1 (this condition can be seen in Theorem A.1 of the [privacy book](https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf), for example), and has been proven to be false for large epsilon (Theorem 4 in [this paper](https://arxiv.org/pdf/1805.06530.pdf)).

The epsilon<1 condition is [correctly implemented](https://github.com/opendp/opendp/blob/main/rust/src/meas/gaussian/mod.rs#L83) in OpenDP itself, so the binary search that happens when sensitivity<=1000 should work. Ideally though, I imagine it would be easier to simply use the analytic gaussian mechanism by default?

**Comment by joshua-oss** [comment]
Thanks for catching these.  The analytic gaussian was not available when we implemented this, but it is easy to add now.  And the override for binary search on sensitivity > 1000 was a hack to get around a slow search. Will fix both.

**Comment by joshua-oss** [comment]
Fixed
