### ISSUE TITLE
Smartnoise Synth Installation Breaking with OpenDP 0.4.0

### ISSUE THREAD

**Issue by AdamHallSAIL** [opendp/smartnoise-sdk#468]
Hey I am loving smartsynth and had a great time playing with it on my OpenDP 0.3.0 build. However, it seems it is only compatible with opendp 0.3.0. When I upgrade to opendp 0.4.0 I run into issues with installation. I'm wondering, will this be updated to run with 0.4.0? It may break my project if not!

Any help is appreciated!

**Comment by lurosenb** [comment]
Hi Adam,

So glad that you're enjoying the tool!!

That's odd - would you mind sharing a stack trace/a bit more about your machine and environment? That'll help me figure out what's going on.

Thanks so much!

**Comment by lurosenb** [comment]
Ah, I see. We need to update our requirements. Thanks for pointing this out!

**Comment by lurosenb** [comment]
Ok, so we will do a new release that fixes the package issue. In the meantime, if you get a package dependency error that looks something like:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
smartnoise-synth 0.2.5 requires opendp<0.4.0,>=0.3.0, but you have opendp 0.4.0 which is incompatible.
```
You can feel free to ignore it! I just verified that all the snsynth tests pass with ```smartnoise-synth=0.2.5```  and ```opendp=0.4.0```, so it shouldn't effect performance to manually upgrade to ```opendp=0.4.0``` despite pip's complaints.

Thanks again for pointing this out - if your use case is not working for any reason, feel free to drop it in here and I can try and help you figure out what's going on : )

**Comment by AdamHallSAIL** [comment]
Ahh thank you! I was a little late in getting back here.  I was originally getting the complaint when I was installing to Windows but I switched to an ubuntu kernel and it just reinstalled opendp to 0.3.0 as part of the pip install process. I'll try upgrading to the new release!

**Comment by joshua-oss** [comment]
We have also updated this in the v0.2.6 release so it will automatically use 0.4.0
