### ISSUE TITLE
SmartNoise Synthesizers description example misses an import

### ISSUE THREAD

**Issue by AlessandroArtoni** [opendp/smartnoise-sdk#470]
In SmartNoise Synthesizers README (https://github.com/opendp/smartnoise-sdk/blob/main/synth/README.md), in MWEM, an import snsynth is missing.

**Comment by joshua-oss** [comment]
Thanks much for reporting this; the docs have been updated to add the missing import!

**Comment by joshua-oss** [comment]
Fixed!
