### ISSUE TITLE
`PUMS.csv` and `PUMS_large.csv` missing from sql `README.md`

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/smartnoise-sdk#501]
These files were dropped from the repo. Should update the `README.md` to grab the right data:
https://github.com/opendp/dp-test-datasets/tree/master/data

**Comment by Shoeboxam** [comment]
Where can you even find PUMS_pid.csv, etc? The README indicates the dp-test-datasets repo, but they were never added there.

**Comment by joshua-oss** [comment]
Thanks for flagging this.  These files are downloaded and generated on the first run of the test fixture, but this was not very clear, and the pointer to the download repository was wrong.  I've updated the README to show how to download and generate without running unit tests:

https://github.com/opendp/smartnoise-sdk/blob/main/datasets/README.md

**Comment by Shoeboxam** [comment]
Thanks!
