### ISSUE TITLE
Error in building + generating samples from PATEGAN synthesizer

### ISSUE THREAD

**Issue by alexWhitworth** [opendp/smartnoise-sdk#508]
I'm running into two errors when using the `'pategan'` synthesizer. One of which appears to be due to an installation on my VM (as I can't reproduce on my laptop), and the other with the library:

## Installation:

```
pip install --upgrade pip
pip install git+https://github.com/ryan112358/private-pgm.git
pip install jax jaxlib smartnoise-synth opendp-smartnoise diffprivlib \
    pytest pyyaml pandasql mlflow connexion ctgan opacus torch
```

## Library error:

```
import pandas as pd
from snsynth import Synthesizer

pums_csv = "./datasets/PUMS_null.csv"
pums_csv2 = "./datasets/PUMS.csv"
pums_nullable = pd.read_csv(pums_csv, index_col=None)
pums_nonulls = pd.read_csv(pums_csv2, index_col=None)
pums_nullable.drop(['pid'], axis=1, inplace=True)

# works fine
synth_dnn = Synthesizer.create('pategan', epsilon=3)
synth_dnn.fit(
    pums_nonulls
    , preprocessor_eps=1.0
    , categorical_columns=['sex','educ','race','married']
    , continuous_columns=['income','age']
    , nullable=True
)
tst = synth_dnn.sample(500)

# error
synth_dnn = Synthesizer.create('pategan', epsilon=3)
synth_dnn.fit(
    pums_nullable
    , preprocessor_eps=1.0
    , categorical_columns=['sex','educ','race','married']
    , continuous_columns=['income','age']
    , nullable=True
)

```

> Traceback (most recent call last):
> >  File "<stdin>", line 1, in <module>
> >  File "/opt/homebrew/lib/python3.10/site-packages/snsynth/pytorch/nn/pategan.py", line 224, in fit
>     self.train(data, transformer=transformer, categorical_columns=categorical_columns, ordinal_columns=ordinal_columns, continuous_columns=continuous_columns, preprocessor_eps=preprocessor_eps, nullable=nullable)
>   File "/opt/homebrew/lib/python3.10/site-packages/snsynth/pytorch/nn/pategan.py", line 161, in train
>     loss_t_real = criterion(output.squeeze(), label_real.double())
>   File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 619, in forward
>     return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
>   File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/functional.py", line 3095, in binary_cross_entropy
>     return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
> RuntimeError: all elements of input should be between 0 and 1

## Error on real dataset:

Unfortunately, I cannot share the real dataset. But, as you can see from the column names below, this is impression/row level data in a digital advertising context.

```
import pandas as pd
from snsynth import Synthesizer

triggerDT = <result from SQL query>

synth_dnn = Synthesizer.create("pategan", epsilon=3.0)
synth_dnn.fit(
    triggerDT
    , preprocessor_eps=1.0
    # , categorical_columns=['dma_code', 'country_code', 'device_type', 'placement_id']
    #,  continuous_columns=['advertiser_id', 'campaign_id', 'ad_group_id', 'creative_id']
    , nullable=True
)

trigger_synth = synth_dnn.sample(500)
```

>       trigger_synth = synth_dnn.sample(500)
> 
> File /opt/conda/envs/py3-primary/lib/python3.8/site-packages/snsynth/pytorch/nn/pategan.py:227, in PATEGAN.sample(self, n_samples)
>     226 def sample(self, n_samples):
> --> 227     return self.generate(n_samples)
> 
> File /opt/conda/envs/py3-primary/lib/python3.8/site-packages/snsynth/pytorch/nn/pategan.py:215, in PATEGAN.generate(self, n)
>     212     noise = torch.randn(self.batch_size, self.latent_dim, device=self.device)
>     213     noise = noise.view(-1, self.latent_dim)
> --> 215     fake_data = self.generator(noise.double())
>     216     data.append(fake_data.detach().cpu().numpy())
>     218 data = np.concatenate(data, axis=0)
> 
> AttributeError: 'PATEGAN' object has no attribute 'generator'
> 

This is confusing to me, as I see the [generator code](https://github.com/opendp/smartnoise-sdk/blob/main/synth/snsynth/pytorch/nn/pategan.py#L98). I also cannot reproduce on my laptop, which returns a different error

> ValueError: number sections must be larger than 0.

## system info:

```
Mac V 12.6.1

$ python3 --version
Python 3.10.8

$ pip list
Package                Version
---------------------- ---------
absl-py                1.3.0
alembic                1.8.1
antlr4-python3-runtime 4.9.3
attrs                  22.1.0
black                  22.3.0
certifi                2022.6.15
charset-normalizer     2.1.0
click                  8.1.3
clickclick             20.10.2
cloudpickle            2.1.0
colorama               0.4.5
connexion              2.14.1
contourpy              1.0.6
crlibm                 1.0.3
ctgan                  0.1.0
cycler                 0.11.0
Cython                 0.29.32
databricks-cli         0.17.3
dbapi                  0.0.14
decorator              5.1.1
diffprivlib            0.5.2
disjoint-set           0.7.3
dlint                  0.10.3
docker                 6.0.1
dynaconf               3.1.11
entrypoints            0.4
flake8                 3.9.2
flake8-assertive       1.2.1
flake8-polyfill        1.0.2
flake8-tuple           0.4.1
Flask                  2.2.2
fonttools              4.36.0
fsspec                 2022.7.1
future                 0.18.2
GDAL                   3.5.2
gitdb                  4.0.9
GitPython              3.1.27
gluonnlp               0.8.1
graphviz               0.17
gunicorn               20.1.0
HeapDict               1.0.1
hvac                   1.0.2
idna                   3.3
impala                 0.2
importlib-metadata     5.0.0
inflection             0.5.1
iniconfig              1.1.1
isort                  5.10.1
itsdangerous           2.1.2
jax                    0.3.25
jaxlib                 0.3.25
Jinja2                 3.1.2
jmespath               1.0.1
joblib                 1.1.0
jsonschema             4.17.1
kazoo                  2.9.0
kiwisolver             1.4.4
knox                   0.1.14
llvmlite               0.39.1
locket                 1.0.0
loguru                 0.6.0
lxml                   4.9.1
MacFSEvents            0.8.1
Mako                   1.2.4
Markdown               3.4.1
MarkupSafe             2.1.1
matplotlib             3.6.2
mccabe                 0.6.1
mlflow                 2.0.1
msgpack                1.0.4
mxnet                  1.6.0
mypy-extensions        0.4.3
networkx               2.8.5
nose                   1.3.7
numba                  0.56.4
numpy                  1.23.2
oauthlib               3.2.2
opacus                 0.14.0
opencv-python          4.6.0.66
opendp                 0.6.1
opendp-smartnoise      0.1.0.3
opt-einsum             3.3.0
pac-synth              0.0.6
packaging              21.3
pandas                 1.4.3
pandasql               0.7.3
partd                  1.3.0
pathspec               0.10.1
pep8-naming            0.10.0
Pillow                 6.2.1
pip                    22.3.1
platformdirs           2.5.2
plotly                 5.10.0
pluggy                 1.0.0
portalocker            2.5.1
private-pgm            0.0.1
protobuf               4.21.9
psutil                 5.9.1
py                     1.11.0
pyaml                  21.10.1
pyarrow                10.0.1
pycodestyle            2.7.0
pycparser              2.21
pyflakes               2.3.1
pyhcl                  0.4.4
PyJWT                  2.6.0
pyparsing              3.0.9
pyrsistent             0.19.2
pytest                 7.1.2
python-dateutil        2.8.2
pytz                   2022.2.1
PyYAML                 5.4.1
querystring-parser     1.2.4
requests               2.28.1
scikit-learn           1.1.2
scipy                  1.9.0
seaborn                0.12.1
setuptools             65.4.1
shap                   0.41.0
shortuuid              1.0.11
six                    1.16.0
sklearn                0.0.post1
slicer                 0.0.7
smartnoise-sql         0.2.6
smartnoise-synth       0.3.2
smmap                  5.0.0
sortedcontainers       2.4.0
SQLAlchemy             1.4.44
sqlparse               0.4.3
tabulate               0.9.0
tblib                  1.7.0
tenacity               8.0.1
tensorflow-addons      0.17.1
threadpoolctl          3.1.0
tomli                  2.0.1
toolz                  0.12.0
torch                  1.13.0
torchvision            0.14.0
tornado                6.1
tqdm                   4.64.0
typeguard              2.13.3
typing                 3.7.4.3
typing_extensions      4.4.0
urllib3                1.26.11
validators             0.20.0
websocket-client       1.4.2
Werkzeug               2.2.2
wheel                  0.37.1
yacs                   0.1.8
zict                   2.2.0
zipp                   3.10.0

```

**Comment by joshua-oss** [comment]
I was able to reproduce the first error.  `MinMaxScaler` and `StandardScaler` were using `None` for null values when the null indicator column was set to `1`, under the assumption the indicator column was enough.  This was a bug, since PyTorch can't use a `None` or `np.nan` in a tensor.  I fixed it to replace the null with 0.0 and tested that it's firing and bringing through nulls now.  Fix has been pushed to smartnoise-synth v0.3.4 on PyPi.

The other issue might be related, since you also have nullable continuous columns there.  Can you check to see if the latest version fixes both issues?

**Comment by alexWhitworth** [comment]
@joshua-oss how do I install `v 0.3.4`? `pip install` still gives me `0.3.2` and `pip install https://github.com/opendp/smartnoise-sdk/tree/main/synth\#egg=smartnoise-synth` gives:

> ERROR: Cannot unpack file /private/tmp/pip-unpack-ii5ax1sx/synth (downloaded from /private/tmp/pip-install-dd6pq7g0/smartnoise-synth_dc7949c1f3144ffcb05cf2ee50cc44b3, content-type: text/html; charset=utf-8); cannot detect archive format
> ERROR: Cannot determine archive format of /private/tmp/pip-install-dd6pq7g0/smartnoise-synth_dc7949c1f3144ffcb05cf2ee50cc44b3

**Comment by joshua-oss** [comment]
Oh, it's up on PyPi now, you can get it with `pip install smartnoise-synth==0.3.4`

**Comment by alexWhitworth** [comment]
`v 0.3.4` appears to resolve for both the PUMS test data and my real data example. thanks!
