### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by jpgoldberg** [opendp/smartnoise-sdk#535]
Is there a reason why required python versions are set to strictly less than 3.11?. I can easily work around this by using 3.10.6, but I am wondering whether support for 3.11 is coming soon. 

(Just be pleased that no one is asking for support for _Windows_ 3.11.)

**Comment by joshua-oss** [comment]
Thanks for the reminder to look at this.  Our GAN synthesizers rely on PyTorch, which doesn't have an official release for Python 3.11 yet.  So we have been waiting for torch support.  However, I just tested, and it's possible to install the nightly PyTorch first:

```
pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

Then, I installed the synthesizers, and all unit tests pass on Python 3.11.  So, I have updated both PyPi packages to allow 3.11.  The refreshed packages are `smartnoise-sql==0.2.9.2` and `smartnoise-synth==0.3.6.2`.
