### ISSUE TITLE
Upgrading to pyyaml 6

### ISSUE THREAD

**Issue by mhauru** [opendp/smartnoise-sdk#565]
There was a recent issue with pyyaml, see https://github.com/yaml/pyyaml/issues/601
The issue was fixed in pyyaml 6.0.1, but currently smartnoise-sql says it needs a version <6. Could this be loosened, and the dependency be upgraded to pyyaml 6?

**Comment by joshua-oss** [comment]
Thanks for reporting this! PyPi packages have been updated to use pyyaml >= 6.0.1
