### ISSUE TITLE
Upgrading smartnoise-sql to use opendp 0.8.0

### ISSUE THREAD

**Issue by mhauru** [opendp/smartnoise-sdk#585]
We ran into an issue where this: https://github.com/opendp/opendp/issues/817 prevents us from using smartnoise-sql on arm64 linux, since opendp isn't built for it. Opendp has a fix for this, but it's only in for 0.8.0, and smartnoise-sql currently depends on ^0.7.0. Could this be upgraded?

**Comment by joshua-oss** [comment]
Should be updated in 1.0.3, released on PyPi now. This should be a fully backwards compatible release, but involved quite a few code changes, so please file bugs if anything breaks.
