### ISSUE TITLE
Compatibility update for opendp 0.10.0 (with polars)

### ISSUE THREAD

**Issue by PaulineMauryL** [opendp/smartnoise-sdk#597]
Hi Smartnoise Team, thanks for the great work here!

We are using smartnoise-sql and opendp in a project and would like to use the new version of opendp (0.10.0) which offers new features with polars. However, smartnoise-sql requires a version of opendp between 0.8.0 and 0.9.0. 

Do you plan to update smartnoise-sql to be compatible with the last opendp version ?

**Comment by joshua-oss** [comment]
Hi @PaulineMauryL, thanks for the reminder to update. The package has been updated now and a pip install --upgrade to the 1.0.4 version should allow use with OpenDP 0.10. Please let us know if you encounter any issues.

**Comment by PaulineMauryL** [comment]
Thank you!
