### ISSUE TITLE
COUNT query results not within 95% error bounds

### ISSUE THREAD

**Issue by ankit-oss** [opendp/smartnoise-sdk#73]
Repeated querying of COUNT query is returning much less than 95% (~91%) of noisy results within the error bounds. Suspect this has something to do with COUNT query results are integer and error bounds are float. 

[Jupyter Notebook](https://github.com/ankit-oss/burdock/blob/master/evaluation/Differential%20Privacy%20Verification.ipynb)

**Code**
import pandas as pd
import DPVerification as dp
import Aggregation as agg
dv = dp.DPVerification(dataset_size=10000)
ag = agg.Aggregation(t=1, repeat_count=10000)
d1_query = "SELECT COUNT(UserId) AS TotalUserCount FROM d1.d1"
d2_query = "SELECT COUNT(UserId) AS TotalUserCount FROM d2.d2"
dp_res, acc_res = dv.dp_query_test(d1_query, d2_query, plot=True, repeat_count=10000)

**Results**
Bounds: [ 9997.004267726446 ,  10002.995732273554 ]
Count of times noisy result within bounds: 9110 / 10000
Count of times noisy result outside bounds: 890 / 10000

**Comment by joshua-oss** [comment]
Fixed in #386
